<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DAPT56R" failures="1" tests="2" name="Test" time="0.02" errors="0" timestamp="2022-10-16T23:12:37 IST">
  <testcase classname="tests.Test1" name="intentionalFail" time="0.003">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at tests.Test1.intentionalFail(Test1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- intentionalFail -->
  <testcase classname="tests.Test1" name="test1_sample" time="0.0"/>
</testsuite> <!-- Test -->
